# Generated by Django 4.2 on 2024-07-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_title', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=500)),
                ('Task', models.TextField(max_length=5000)),
            ],
        ),
    ]
